-- ==============================================================================
-- سكريبت إنشاء «صندوق استقبال مسحوحات السكانر»
-- (وسيط بين السكانر الفعلي المربوط بجهاز الكمبيوتر والموقع: الورقة تُسكَن محليًا
--  ثم يرفعها «الجسر المحلي» هنا، والموقع يستقبلها ويربطها بصاحب الأمر التنفيذي)
--
-- انسخ هذا الكود بالكامل والصقه في Supabase -> SQL Editor ثم اضغط Run
-- السكريبت آمن لإعادة التشغيل (idempotent) — لا يحذف أي بيانات موجودة.
--
-- ينشئ:
--   1. جدول public.scanner_inbox          (كل صف = ورقة ممسوحة ووصلت من السكانر)
--   2. بكت تخزين عام public "scanner-inbox"  (ملفات المسحوحات)
--   3. سياسات RLS للجدول والبكت (قراءة/إدراج/تحديث) للأنون والمستخدم
-- ==============================================================================

-- 1. صندوق الاستقبال (كل صف = ملف مسموح وصل من السكانر عبر الجسر المحلي)
CREATE TABLE IF NOT EXISTS public.scanner_inbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_path TEXT NOT NULL,                            -- مسار الملف داخل البكت (مثال: 1728....pdf)
  file_url TEXT,                                      -- الرابط العام للملف
  file_name TEXT,                                     -- اسم الملف الأصلي (مثال: Scan0001.pdf)
  file_mime TEXT,                                     -- image/jpeg أو application/pdf
  file_size BIGINT,                                   -- حجم الملف بالبايت
  status TEXT NOT NULL DEFAULT 'pending',             -- pending = بانتظار الاستقبال / done = أُضيف لأرشيف الأوامر
  scanned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),      -- وقت وصول المسحوبة من السكانر
  processed_at TIMESTAMPTZ,                           -- وقت ربطها بأمر تنفيذي
  processed_by TEXT,                                  -- من استقبلها
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- فهرس للبحث السريع في المسحوحات المعلّقة
CREATE INDEX IF NOT EXISTS idx_scanner_inbox_status
  ON public.scanner_inbox (status, scanned_at DESC);

-- 2. سياسات أمان RLS
ALTER TABLE public.scanner_inbox ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read scanner inbox" ON public.scanner_inbox;
DROP POLICY IF EXISTS "Allow insert scanner inbox" ON public.scanner_inbox;
DROP POLICY IF EXISTS "Allow update scanner inbox" ON public.scanner_inbox;

CREATE POLICY "Allow read scanner inbox"
  ON public.scanner_inbox FOR SELECT
  TO anon, authenticated USING (true);

CREATE POLICY "Allow insert scanner inbox"
  ON public.scanner_inbox FOR INSERT
  TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Allow update scanner inbox"
  ON public.scanner_inbox FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

GRANT ALL ON public.scanner_inbox TO anon, authenticated, postgres, service_role;
GRANT ALL ON SEQUENCE public.scanner_inbox_id_seq TO anon, authenticated, postgres, service_role;

-- 3. بكت التخزين العام لملفات المسحوحات
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'scanner-inbox',
  'scanner-inbox',
  true,
  52428800, -- 50MB لكل مسحوبة
  ARRAY['application/pdf', 'image/jpeg', 'image/png']
) ON CONFLICT (id) DO NOTHING;

-- سياسات القراءة والكتابة على البكت (مطلوب للرفع من «الجسر المحلي» والتحميل من الموقع)
DROP POLICY IF EXISTS "Allow read scanner inbox files" ON storage.objects;
DROP POLICY IF EXISTS "Allow upload scanner inbox files" ON storage.objects;

CREATE POLICY "Allow read scanner inbox files"
  ON storage.objects FOR SELECT
  TO public USING (bucket_id = 'scanner-inbox');

CREATE POLICY "Allow upload scanner inbox files"
  ON storage.objects FOR INSERT
  TO anon, authenticated WITH CHECK (bucket_id = 'scanner-inbox');

-- تحديث كاش PostgREST
NOTIFY pgrst, 'reload schema';