-- ==============================================================================
-- سكريبت إنشاء أرشيف الأوامر التنفيذية
-- (كل شخص له ملف PDF واحد كبير يتحدّث بإضافة الأوامر الجديدة إليه)
--
-- انسخ هذا الكود بالكامل والصقه في Supabase -> SQL Editor ثم اضغط Run
-- السكريبت آمن لإعادة التشغيل (idempotent) — لا يحذف أي بيانات موجودة.
--
-- ينشئ:
--   1. جدول public.executive_order_persons  (الشخص ↔ الملف)
--   2. جدول public.executive_orders        (الأوامر المرتبطة بالشخص)
--   3. بكت تخزين عام public "executive-orders"  (ملفات PDF الأرشيف)
--   4. سياسات RLS للجداول والبكت (قراءة/إدراج/تحديث) للمستخدم والآنون
-- ==============================================================================

-- 1. الأشخاص (كل صف = شخص له ملف PDF واحد)
CREATE TABLE IF NOT EXISTS public.executive_order_persons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  full_name_norm TEXT NOT NULL DEFAULT '',            -- نسخة مطبّعة من الاسم للبحث المرن
  file_path TEXT,                                      -- مسار ملف PDF داخل البكت (مثال: 12/file.pdf)
  file_url TEXT,                                       -- الرابط العام للملف
  page_count INTEGER NOT NULL DEFAULT 0,               -- عدد صفحات ملف الشخص الحالي
  order_count INTEGER NOT NULL DEFAULT 0,              -- عدد الأوامر المضافة لهذا الشخص
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. الأوامر التنفيذية (كل صف = أمر أُضيف إلى ملف شخص)
CREATE TABLE IF NOT EXISTS public.executive_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id BIGINT NOT NULL REFERENCES public.executive_order_persons(id) ON DELETE CASCADE,
  order_title TEXT,
  order_date DATE,
  source_mime TEXT,                                    -- نوع ملف المصدر (image/jpeg أو application/pdf)
  original_filename TEXT,                              -- اسم الملف الأصلي المرفوع
  page_start INTEGER,                                  -- أول صفحة للأمر داخل ملف الشخص
  page_end INTEGER,                                    -- آخر صفحة للأمر داخل ملف الشخص
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- فهارس للبحث السريع
CREATE INDEX IF NOT EXISTS idx_executive_order_persons_norm
  ON public.executive_order_persons (full_name_norm);
CREATE INDEX IF NOT EXISTS idx_executive_orders_person_id
  ON public.executive_orders (person_id);

-- 3. سياسات أمان RLS
ALTER TABLE public.executive_order_persons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.executive_orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read executive order persons" ON public.executive_order_persons;
DROP POLICY IF EXISTS "Allow insert executive order persons" ON public.executive_order_persons;
DROP POLICY IF EXISTS "Allow update executive order persons" ON public.executive_order_persons;

DROP POLICY IF EXISTS "Allow read executive orders items" ON public.executive_orders;
DROP POLICY IF EXISTS "Allow insert executive orders items" ON public.executive_orders;

CREATE POLICY "Allow read executive order persons"
  ON public.executive_order_persons FOR SELECT
  TO anon, authenticated USING (true);

CREATE POLICY "Allow insert executive order persons"
  ON public.executive_order_persons FOR INSERT
  TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Allow update executive order persons"
  ON public.executive_order_persons FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow read executive orders items"
  ON public.executive_orders FOR SELECT
  TO anon, authenticated USING (true);

CREATE POLICY "Allow insert executive orders items"
  ON public.executive_orders FOR INSERT
  TO anon, authenticated WITH CHECK (true);

GRANT ALL ON public.executive_order_persons TO anon, authenticated, postgres, service_role;
GRANT ALL ON public.executive_orders TO anon, authenticated, postgres, service_role;
GRANT ALL ON SEQUENCE public.executive_order_persons_id_seq TO anon, authenticated, postgres, service_role;
GRANT ALL ON SEQUENCE public.executive_orders_id_seq TO anon, authenticated, postgres, service_role;

-- 4. بكت التخزين العام لملفات الأرشيف
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'executive-orders',
  'executive-orders',
  true,
  104857600, -- 100MB
  ARRAY['application/pdf', 'image/jpeg', 'image/png']
) ON CONFLICT (id) DO NOTHING;

-- سياسات القراءة والكتابة على البكت (مطلوب للرفع/الاستبدال عبر upsert)
DROP POLICY IF EXISTS "Allow read executive orders files" ON storage.objects;
DROP POLICY IF EXISTS "Allow upload executive orders files" ON storage.objects;
DROP POLICY IF EXISTS "Allow replace executive orders files" ON storage.objects;

CREATE POLICY "Allow read executive orders files"
  ON storage.objects FOR SELECT
  TO public USING (bucket_id = 'executive-orders');

CREATE POLICY "Allow upload executive orders files"
  ON storage.objects FOR INSERT
  TO anon, authenticated WITH CHECK (bucket_id = 'executive-orders');

CREATE POLICY "Allow replace executive orders files"
  ON storage.objects FOR UPDATE
  TO anon, authenticated USING (bucket_id = 'executive-orders') WITH CHECK (bucket_id = 'executive-orders');

-- تحديث كاش PostgREST
NOTIFY pgrst, 'reload schema';