-- ============================================================================
-- أرشيف مفردات مرتب الموظفين - قسم مستقل جديد
-- (Independent section: does NOT touch letters / QR / scanner / templates / numbering)
--
-- التشغيل: من Supabase Dashboard -> SQL Editor -> New query -> Run
-- ============================================================================

-- ---------------------------------------------------------------
-- 1) الجدول الرئيسي للأرشيف
-- ربط الملف بالموظف يتم عبر عمود computer_number
-- (مفتاح الربط) + employee_name، بينما Mirror للبنية داخل Storage:
--   employee-salary-archive/employee-salaries/{computer_number}/{year}/{month}/{file}
-- ---------------------------------------------------------------
create table if not exists public.employee_salary_archive (
  id bigint generated by default as identity primary key,
  employee_name text not null,
  computer_number text not null,
  year integer not null,
  month integer not null check (month between 1 and 12),
  sequence integer not null default 1,
  file_url text not null,
  preview_url text,
  preview_urls text[] not null default '{}',
  page_count integer not null default 1,
  file_path text,
  original_filename text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (computer_number, year, month, sequence)
);

-- فهارس للأداء (بحث سريع، ترتيب، فلاتر)
create index if not exists idx_esa_member
  on public.employee_salary_archive (computer_number, employee_name);

create index if not exists idx_esa_year_month
  on public.employee_salary_archive (year, month);

create index if not exists idx_esa_name_search
  on public.employee_salary_archive using gin (to_tsvector('simple', employee_name));

-- ---------------------------------------------------------------
-- 2) قائمة المراجعة "يحتاج مراجعة"
-- الملفات التي لا يمكن استخراج بياناتها بشكل موثوق تذهب هنا
-- ولا يتم إضافتها للأرشيف حتى تصحيحها يدويًا.
-- ---------------------------------------------------------------
create table if not exists public.employee_salary_imports (
  id bigint generated by default as identity primary key,
  file_name text not null,
  storage_path text,
  file_url text,
  page_count integer,
  extracted_name text,
  extracted_computer_number text,
  extracted_year integer,
  extracted_month integer,
  status text not null default 'needs_review' check (status in ('needs_review','imported','discarded')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_esi_status
  on public.employee_salary_imports (status);

-- ---------------------------------------------------------------
-- 3) Row Level Security
-- ملاحظة: النظام يستخدم تسجيل الدخول الحالي (على مستوى التطبيق)
-- ولا يستخدم جلسات Supabase Auth، لذلك تتبع السياسات نفس نمط باقي
-- جداول النظام (anon + authenticated) مع الحماية من App.jsx نفسه
-- الذي لا يعرض لوحة الإدارة إلا بعد تسجيل الدخول.
-- ---------------------------------------------------------------
alter table public.employee_salary_archive enable row level security;
alter table public.employee_salary_imports enable row level security;

drop policy if exists "esa_select_for_app" on public.employee_salary_archive;
create policy "esa_select_for_app"
  on public.employee_salary_archive for select
  to anon, authenticated using (true);

drop policy if exists "esa_insert_for_app" on public.employee_salary_archive;
create policy "esa_insert_for_app"
  on public.employee_salary_archive for insert
  to anon, authenticated with check (true);

drop policy if exists "esa_update_for_app" on public.employee_salary_archive;
create policy "esa_update_for_app"
  on public.employee_salary_archive for update
  to anon, authenticated using (true) with check (true);

drop policy if exists "esa_delete_for_app" on public.employee_salary_archive;
create policy "esa_delete_for_app"
  on public.employee_salary_archive for delete
  to anon, authenticated using (true);

drop policy if exists "esi_select_for_app" on public.employee_salary_imports;
create policy "esi_select_for_app"
  on public.employee_salary_imports for select
  to anon, authenticated using (true);

drop policy if exists "esi_insert_for_app" on public.employee_salary_imports;
create policy "esi_insert_for_app"
  on public.employee_salary_imports for insert
  to anon, authenticated with check (true);

drop policy if exists "esi_update_for_app" on public.employee_salary_imports;
create policy "esi_update_for_app"
  on public.employee_salary_imports for update
  to anon, authenticated using (true) with check (true);

drop policy if exists "esi_delete_for_app" on public.employee_salary_imports;
create policy "esi_delete_for_app"
  on public.employee_salary_imports for delete
  to anon, authenticated using (true);

-- ---------------------------------------------------------------
-- 4) Storage Bucket جديد مستقل (لا يلامس bucket "faculty-salaries" القديم)
-- البنية داخل الـ bucket:
--   employee-salaries/{computer_number}/{year}/{month}/{file}.pdf
--   employee-salaries/{computer_number}/{year}/{month}/previews/{n}.jpg
-- ---------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('employee-salary-archive', 'employee-salary-archive', true)
on conflict (id) do nothing;

drop policy if exists "esa_upload_objects" on storage.objects;
create policy "esa_upload_objects"
  on storage.objects for insert
  to anon, authenticated with check (bucket_id = 'employee-salary-archive');

drop policy if exists "esa_read_objects" on storage.objects;
create policy "esa_read_objects"
  on storage.objects for select
  to public using (bucket_id = 'employee-salary-archive');

drop policy if exists "esa_update_objects" on storage.objects;
create policy "esa_update_objects"
  on storage.objects for update
  to anon, authenticated
  using (bucket_id = 'employee-salary-archive')
  with check (bucket_id = 'employee-salary-archive');

drop policy if exists "esa_delete_objects" on storage.objects;
create policy "esa_delete_objects"
  on storage.objects for delete
  to anon, authenticated using (bucket_id = 'employee-salary-archive');