create table if not exists public.faculty_salary_pages (
  id bigint generated by default as identity primary key,
  file_name text not null,
  file_url text not null,
  period_year integer not null,
  period_month integer not null check (period_month between 1 and 12),
  page_number integer not null,
  text_content text not null,
  page_image_url text,
  created_at timestamptz not null default now()
);

alter table public.faculty_salary_pages
  add column if not exists page_image_url text;

alter table public.faculty_salary_pages enable row level security;

drop policy if exists "Allow authenticated users to read faculty salary pages" on public.faculty_salary_pages;
drop policy if exists "Allow authenticated users to insert faculty salary pages" on public.faculty_salary_pages;

create policy "Allow program users to read faculty salary pages"
  on public.faculty_salary_pages for select
  to anon, authenticated using (true);

create policy "Allow program users to insert faculty salary pages"
  on public.faculty_salary_pages for insert
  to anon, authenticated with check (true);

insert into storage.buckets (id, name, public)
values ('faculty-salaries', 'faculty-salaries', true)
on conflict (id) do nothing;

drop policy if exists "Allow authenticated users to upload faculty salary files" on storage.objects;
drop policy if exists "Allow public access to faculty salary files" on storage.objects;

create policy "Allow program users to upload faculty salary files"
  on storage.objects for insert
  to anon, authenticated with check (bucket_id = 'faculty-salaries');

create policy "Allow program users to read faculty salary files"
  on storage.objects for select
  to public using (bucket_id = 'faculty-salaries');
