import { useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { styles } from "./styles";
import { supabase } from "../supabaseClient";

const MONTHS = ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"];
const EMPLOYEES = [
  { id: 1, name: "صفاء عبد الوهاب", job: "مسؤول مرتبات", department: "قسم الاستحقاقات" },
  { id: 2, name: "ياسمين عبد الوهاب", job: "مسؤول فواتير", department: "قسم الاستحقاقات" },
  { id: 3, name: "حورية فؤاد", job: "مسؤول إجازات", department: "قسم الاستحقاقات" },
  { id: 4, name: "أماني صلاح", job: "مسؤول مطالبات", department: "قسم الاستحقاقات" },
  { id: 5, name: "عبد الله السعيد", job: "مسؤول زمالة", department: "قسم الاستحقاقات" },
  { id: 6, name: "جهاد عاطف", job: "مسؤول أرشيف", department: "قسم الاستحقاقات" },
];
const AXES = [
  { key: "digital", label: "الكفاءة الرقمية", weight: 30, color: "#2563EB", items: ["إجادة استخدام الأنظمة الإلكترونية", "سرعة ودقة إدخال البيانات", "تحديث السجلات والملفات الإلكترونية", "التعامل مع الطلبات الإلكترونية", "رفع وتنظيم المستندات إلكترونياً"] },
  { key: "quality", label: "جودة ودقة العمل", weight: 25, color: "#7C3AED", items: ["دقة البيانات والمعلومات", "انخفاض نسبة الأخطاء", "مراجعة المعاملات قبل اعتمادها", "الالتزام بالإجراءات والتعليمات", "جودة المخرجات النهائية"] },
  { key: "office", label: "خدمات المكتب", weight: 25, color: "#047857", items: ["سرعة خدمة الموظفين والمراجعين", "إنجاز الطلبات في الوقت المحدد", "حسن التعامل والتواصل", "متابعة الطلبات حتى إتمامها", "تنظيم الملفات والمستندات"] },
  { key: "discipline", label: "الالتزام والانضباط", weight: 10, color: "#B45309", items: ["الالتزام بمواعيد العمل", "الالتزام بالتعليمات", "تحمل المسؤولية", "المحافظة على سرية البيانات"] },
  { key: "initiative", label: "التطوير والمبادرة", weight: 10, color: "#0891B2", items: ["اقتراح تحسينات للعمل", "المبادرة في حل المشكلات", "تعلم الأنظمة والمهارات الجديدة", "تطوير العمل الإلكتروني"] },
];
const AXIS_LABELS = AXES.map((axis) => axis.label);

function scoreStyle(score) {
  if (score >= 90) return { color: "#047857", background: "#D1FAE5", grade: "ممتاز" };
  if (score >= 80) return { color: "#1D4ED8", background: "#DBEAFE", grade: "جيد جداً" };
  if (score >= 70) return { color: "#C2410C", background: "#FFEDD5", grade: "جيد" };
  if (score >= 60) return { color: "#A16207", background: "#FEF3C7", grade: "مقبول" };
  return { color: "#DC2626", background: "#FEE2E2", grade: "يحتاج إلى تحسين" };
}
function clamp(value, min = 0, max = 100) { return Math.min(max, Math.max(min, Number(value) || 0)); }
function emptyScores() { return Object.fromEntries(AXES.map((axis) => [axis.key, axis.items.map(() => 0)])); }
function axisScores(evaluation) {
  const stored = evaluation?.detail_scores;
  if (stored && typeof stored === "object") return stored;
  return {
    digital: [evaluation?.completion_rate, evaluation?.on_time_rate, evaluation?.accuracy_rate, evaluation?.speed_rate, evaluation?.upload_rate].map((v) => clamp(v) / 20),
    quality: [evaluation?.accuracy_rate, evaluation?.accuracy_rate, evaluation?.review_rate, evaluation?.organization_rate, evaluation?.accuracy_rate].map((v) => clamp(v) / 20),
    office: [evaluation?.speed_rate, evaluation?.on_time_rate, evaluation?.review_rate, evaluation?.organization_rate, evaluation?.completion_rate].map((v) => clamp(v) / 20),
    discipline: [evaluation?.on_time_rate, evaluation?.organization_rate, evaluation?.review_rate, evaluation?.upload_rate].map((v) => clamp(v) / 20),
    initiative: [evaluation?.organization_rate, evaluation?.speed_rate, evaluation?.accuracy_rate, evaluation?.upload_rate].map((v) => clamp(v) / 20),
  };
}
function aggregateScores(evaluation, tasks) {
  const scores = axisScores(evaluation);
  const result = {};
  AXES.forEach((axis) => {
    const values = scores[axis.key] || [];
    result[axis.key] = values.length ? Math.round((values.reduce((sum, value) => sum + clamp(value, 0, 5), 0) / values.length) * 20) : 0;
  });
  if (!evaluation && tasks.length) result.digital = result.office = Math.round((tasks.filter((task) => task.status === "مكتمل").length / tasks.length) * 100);
  return result;
}
function overallScore(values) { return Math.round(AXES.reduce((sum, axis) => sum + values[axis.key] * axis.weight, 0) / 100); }

function BarChart({ rows, comparison = false }) {
  const width = 640; const height = 250; const chartHeight = 175;
  return <svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="مقارنة محاور الأداء" style={{ width: "100%", minHeight: 230 }}>
    {comparison ? rows.map((row, index) => <g key={row.name}><text x={width - 8} y={24 + index * 35} textAnchor="end" fontSize="12" fill="#475569">{row.name}</text><rect x={150} y={11 + index * 35} width={width - 180} height="18" rx="8" fill="#E2E8F0" />{row.values.map((value, valueIndex) => <rect key={valueIndex} x={150} y={11 + index * 35 + valueIndex * 4} width={(width - 180) * clamp(value) / 100} height="4" fill={AXES[valueIndex].color} />)}</g>) : rows.map((row, index) => { const barWidth = 74; const x = 35 + index * 120; return <g key={row.label}><rect x={x} y={chartHeight - (chartHeight * row.value / 100)} width={barWidth} height={chartHeight * row.value / 100} rx="8" fill={row.color} /><text x={x + barWidth / 2} y={chartHeight + 22} textAnchor="middle" fontSize="11" fill="#475569">{row.label}</text><text x={x + barWidth / 2} y={chartHeight - (chartHeight * row.value / 100) - 8} textAnchor="middle" fontSize="12" fontWeight="bold" fill={row.color}>{row.value}%</text></g>; })}
  </svg>;
}
function RadarChart({ values }) {
  const center = 150; const radius = 105; const points = values.map((value, index) => { const angle = (-Math.PI / 2) + (index * 2 * Math.PI / 5); return `${center + Math.cos(angle) * radius * value / 100},${center + Math.sin(angle) * radius * value / 100}`; }).join(" ");
  return <svg viewBox="0 0 300 300" style={{ width: "100%", maxHeight: 280 }}><polygon points={AXES.map((_, index) => { const angle = (-Math.PI / 2) + (index * 2 * Math.PI / 5); return `${center + Math.cos(angle) * radius},${center + Math.sin(angle) * radius}`; }).join(" ")} fill="#F8FAFC" stroke="#CBD5E1" />{[25, 50, 75].map((level) => <polygon key={level} points={AXES.map((_, index) => { const angle = (-Math.PI / 2) + (index * 2 * Math.PI / 5); return `${center + Math.cos(angle) * radius * level / 100},${center + Math.sin(angle) * radius * level / 100}`; }).join(" ")} fill="none" stroke="#E2E8F0" />)}<polygon points={points} fill="#2563EB44" stroke="#2563EB" strokeWidth="3" />{AXES.map((axis, index) => { const angle = (-Math.PI / 2) + (index * 2 * Math.PI / 5); return <text key={axis.key} x={center + Math.cos(angle) * 137} y={center + Math.sin(angle) * 137} textAnchor="middle" fontSize="11" fill="#475569">{axis.label}</text>; })}</svg>;
}
function LineChart({ values }) { return <svg viewBox="0 0 720 230" style={{ width: "100%", minHeight: 220 }}><polyline points={values.map((value, index) => `${30 + index * 60},${195 - value * 1.6}`).join(" ")} fill="none" stroke="#2563EB" strokeWidth="4" />{values.map((value, index) => <g key={index}><circle cx={30 + index * 60} cy={195 - value * 1.6} r="5" fill="#fff" stroke="#2563EB" strokeWidth="3" /><text x={30 + index * 60} y="218" textAnchor="middle" fontSize="10" fill="#64748B">{index + 1}</text></g>)}</svg>; }
function Donut({ values }) { const total = values.reduce((sum, value) => sum + value, 0) || 1; let offset = 0; const gradients = values.map((value, index) => { const start = offset; offset += value / total * 100; return `${AXES[index].color} ${start}% ${offset}%`; }).join(", "); return <div style={{ width: 170, height: 170, borderRadius: "50%", background: `conic-gradient(${gradients})`, display: "grid", placeItems: "center" }}><div style={{ width: 112, height: 112, borderRadius: "50%", background: "#fff", display: "grid", placeItems: "center", textAlign: "center" }}><strong style={{ fontSize: 25 }}>{Math.round(total / values.length)}%</strong><small>متوسط المحاور</small></div></div>; }

export default function EmployeePerformanceDashboard() {
  const [evaluations, setEvaluations] = useState([]);
  const [tasks, setTasks] = useState([]);
  const [selectedId, setSelectedId] = useState(1);
  const [compareIds, setCompareIds] = useState([1, 2]);
  const [search, setSearch] = useState("");
  const [jobFilter, setJobFilter] = useState("all");
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ month: new Date().getMonth() + 1, year: new Date().getFullYear(), scores: emptyScores(), notes: "" });
  const [error, setError] = useState("");

  useEffect(() => { Promise.all([supabase.from("performance_evaluations").select("*").order("evaluation_year", { ascending: false }), supabase.from("employee_tasks").select("*")]).then(([evaluationResult, taskResult]) => { if (evaluationResult.error || taskResult.error) { console.error(evaluationResult.error || taskResult.error); setError("تعذر تحميل بيانات التقييم من Supabase."); } setEvaluations(evaluationResult.data || []); setTasks(taskResult.data || []); }); }, []);
  const selectedEmployee = EMPLOYEES.find((employee) => employee.id === selectedId) || EMPLOYEES[0];
  const latest = evaluations.find((evaluation) => Number(evaluation.employee_id) === selectedId);
  const selectedValues = aggregateScores(latest, tasks.filter((task) => task.employee_id === selectedId));
  const selectedOverall = overallScore(selectedValues);
  const selectedStyle = scoreStyle(selectedOverall);
  const filteredEmployees = EMPLOYEES.filter((employee) => employee.name.includes(search) && (jobFilter === "all" || employee.job === jobFilter));
  const ranking = EMPLOYEES.map((employee) => { const evaluation = evaluations.find((item) => Number(item.employee_id) === employee.id); const values = aggregateScores(evaluation, tasks.filter((task) => task.employee_id === employee.id)); return { ...employee, values, overall: overallScore(values) }; }).sort((a, b) => b.overall - a.overall);
  const monthly = MONTHS.map((_, index) => { const evaluation = evaluations.find((item) => Number(item.employee_id) === selectedId && Number(item.evaluation_year) === new Date().getFullYear() && (item.evaluation_month === MONTHS[index] || Number(item.evaluation_month) === index + 1)); return evaluation ? overallScore(aggregateScores(evaluation, [])) : 0; });
  const detailScores = axisScores(latest);
  const strengths = AXES.flatMap((axis) => axis.items.map((item, index) => ({ item, score: clamp(detailScores[axis.key]?.[index], 0, 5) }))).filter((item) => item.score >= 4).sort((a, b) => b.score - a.score).slice(0, 5);
  const improvements = AXES.flatMap((axis) => axis.items.map((item, index) => ({ item, score: clamp(detailScores[axis.key]?.[index], 0, 5) }))).filter((item) => item.score > 0 && item.score <= 2).sort((a, b) => a.score - b.score).slice(0, 5);
  const saveEvaluation = async (event) => { event.preventDefault(); const averages = Object.fromEntries(AXES.map((axis) => [axis.key, Math.round((form.scores[axis.key].reduce((sum, value) => sum + clamp(value, 0, 5), 0) / axis.items.length) * 20)])); const payload = { employee_id: selectedId, evaluation_month: MONTHS[form.month - 1], evaluation_year: Number(form.year), completion_rate: averages.digital, on_time_rate: averages.discipline, accuracy_rate: averages.quality, speed_rate: averages.office, review_rate: averages.quality, upload_rate: averages.digital, organization_rate: averages.office, total_score: overallScore(averages), grade: scoreStyle(overallScore(averages)).grade, detail_scores: form.scores, notes: form.notes || null }; const { data, error: saveError } = await supabase.from("performance_evaluations").insert(payload).select().single(); if (saveError) { console.error(saveError); setError("تعذر حفظ التقييم التفصيلي."); return; } setEvaluations((current) => [data, ...current]); setShowForm(false); };
  const exportExcel = () => { const rows = ranking.map((row, index) => ({ الترتيب: index + 1, الموظف: row.name, الوظيفة: row.job, "التقييم العام": `${row.overall}%`, "الكفاءة الرقمية": `${row.values.digital}%`, "جودة العمل": `${row.values.quality}%`, "خدمات المكتب": `${row.values.office}%`, الالتزام: `${row.values.discipline}%`, التطوير: `${row.values.initiative}%`, المستوى: scoreStyle(row.overall).grade })); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(rows), "مقارنة الموظفين"); XLSX.writeFile(workbook, "تقرير-تقييم-الموظفين.xlsx"); };
  const kpis = AXES.map((axis) => ({ ...axis, value: selectedValues[axis.key] }));
  return <div dir="rtl">
    <div style={styles.card}>
      <div style={styles.cardHeader}><div><div style={styles.breadcrumb}>قسم الاستحقاقات / تقييم الأداء</div><h2 style={styles.cardTitle}>📊 تقييم الأداء الإلكتروني وخدمات المكتب</h2><p style={styles.cardSub}>لوحة قياس مؤسسية متوافقة مع مبادئ ISO 9001 وCSAT وSLA</p></div><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button style={styles.primaryButton} onClick={() => window.print()}>🖨️ طباعة التقرير</button><button style={styles.secondaryButton} onClick={() => window.print()}>📄 تصدير PDF</button><button style={styles.excelButton} onClick={exportExcel}>📊 تصدير Excel</button></div></div>
      {error && <div style={styles.errorBox}>{error}</div>}
      <div style={{ display: "flex", gap: 10, flexWrap: "wrap", padding: 14, background: "#F8FAFC", borderRadius: 12, marginBottom: 18 }}><select style={styles.input} value={selectedId} onChange={(event) => setSelectedId(Number(event.target.value))}>{EMPLOYEES.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select><span style={{ alignSelf: "center", color: "#64748B" }}>{selectedEmployee.job} · {selectedEmployee.department} · فترة التقييم: {latest ? `${latest.evaluation_month} ${latest.evaluation_year}` : "لا يوجد تقييم مسجل"}</span><button style={styles.primaryButton} onClick={() => setShowForm(true)}>＋ إضافة تقييم تفصيلي</button></div>
      <div style={{ ...styles.card, margin: 0, background: "linear-gradient(135deg,#0F2942,#2563EB)", color: "#fff" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 20 }}><div><h1 style={{ margin: 0, fontSize: 28 }}>{selectedEmployee.name}</h1><p style={{ margin: "8px 0 0", opacity: .8 }}>{selectedEmployee.job} · {selectedEmployee.department}</p></div><div style={{ textAlign: "center" }}><div style={{ fontSize: 50, fontWeight: 900 }}>{selectedOverall}%</div><div>{selectedStyle.grade}</div></div></div></div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))", gap: 14, margin: "18px 0" }}><div style={{ ...styles.card, margin: 0, textAlign: "center", background: selectedStyle.background, color: selectedStyle.color }}><strong style={{ fontSize: 32 }}>{selectedOverall}%</strong><div>التقييم العام</div></div>{kpis.map((kpi) => <div key={kpi.key} style={{ ...styles.card, margin: 0, textAlign: "center" }}><div style={{ color: kpi.color, fontSize: 28 }}>{kpi.key === "digital" ? "💻" : kpi.key === "quality" ? "🎯" : kpi.key === "office" ? "🏢" : kpi.key === "discipline" ? "⏱️" : "💡"}</div><strong style={{ fontSize: 27, color: kpi.color }}>{kpi.value}%</strong><div>{kpi.label}</div><div style={{ height: 7, background: "#E2E8F0", borderRadius: 10, marginTop: 10 }}><div style={{ width: `${kpi.value}%`, height: "100%", background: kpi.color, borderRadius: 10 }} /></div></div>)}</div>
      <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1.2fr) minmax(260px,.8fr)", gap: 18 }}><div style={{ ...styles.card, margin: 0 }}><h3 style={styles.cardTitle}>مقارنة محاور الأداء</h3><BarChart rows={kpis} /></div><div style={{ ...styles.card, margin: 0, textAlign: "center" }}><h3 style={styles.cardTitle}>ملف الأداء العام</h3><RadarChart values={kpis.map((kpi) => kpi.value)} /></div></div>
      <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1.2fr) minmax(260px,.8fr)", gap: 18, marginTop: 18 }}><div style={{ ...styles.card, margin: 0 }}><h3 style={styles.cardTitle}>تطور أداء الموظف</h3><LineChart values={monthly} /><div style={{ display: "flex", justifyContent: "space-between", color: "#64748B", fontSize: 11 }}>{MONTHS.map((month) => <span key={month}>{month}</span>)}</div></div><div style={{ ...styles.card, margin: 0 }}><h3 style={styles.cardTitle}>توزيع عناصر التقييم</h3><div style={{ display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" }}><Donut values={kpis.map((kpi) => kpi.value)} /><div>{kpis.map((kpi) => <div key={kpi.key} style={{ margin: "8px 0", color: kpi.color, fontSize: 13 }}>● {kpi.label}: {kpi.value}%</div>)}</div></div></div></div>
      <div style={{ ...styles.card, marginTop: 18 }}><h3 style={styles.cardTitle}>📋 التقرير التفصيلي</h3>{AXES.map((axis) => <div key={axis.key} style={{ padding: 16, border: "1px solid #E2E8F0", borderRadius: 12, marginTop: 12 }}><div style={{ display: "flex", justifyContent: "space-between", fontWeight: 800 }}><span>{axis.label}</span><span style={{ color: axis.color }}>وزن {axis.weight}% · {selectedValues[axis.key]}%</span></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(190px,1fr))", gap: 8, marginTop: 12 }}>{axis.items.map((item, index) => <div key={item} style={{ padding: 9, background: "#F8FAFC", borderRadius: 8, fontSize: 12 }}>{item}<strong style={{ display: "block", color: axis.color, marginTop: 4 }}>{clamp(detailScores[axis.key]?.[index], 0, 5)}/5</strong></div>)}</div></div>)}</div>
      <div style={{ ...styles.card, marginTop: 18 }}><h3 style={styles.cardTitle}>👥 مقارنة الموظفين</h3><div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 14 }}><input style={styles.input} placeholder="بحث باسم الموظف" value={search} onChange={(event) => setSearch(event.target.value)} /><select style={styles.input} value={jobFilter} onChange={(event) => setJobFilter(event.target.value)}><option value="all">كل الوظائف</option>{[...new Set(EMPLOYEES.map((employee) => employee.job))].map((job) => <option key={job}>{job}</option>)}</select></div><div style={{ overflowX: "auto" }}><table style={styles.table}><thead><tr><th style={styles.th}>#</th><th style={styles.th}>الموظف</th><th style={styles.th}>الوظيفة</th><th style={styles.th}>العام</th>{AXES.map((axis) => <th key={axis.key} style={styles.th}>{axis.label}</th>)}<th style={styles.th}>المستوى</th></tr></thead><tbody>{ranking.filter((row) => filteredEmployees.some((employee) => employee.id === row.id)).map((row, index) => <tr key={row.id} style={styles.tr}><td style={styles.td}>{index + 1}</td><td style={styles.td}><button style={{ border: 0, background: "transparent", color: "#2563EB", cursor: "pointer", fontWeight: 800 }} onClick={() => setSelectedId(row.id)}>{row.name}</button><input type="checkbox" checked={compareIds.includes(row.id)} onChange={() => setCompareIds((current) => current.includes(row.id) ? current.filter((id) => id !== row.id) : [...current, row.id])} /></td><td style={styles.td}>{row.job}</td><td style={styles.td}>{row.overall}%</td>{AXES.map((axis) => <td key={axis.key} style={styles.td}>{row.values[axis.key]}%</td>)}<td style={styles.td}><span style={{ ...styles.statusBadge, color: scoreStyle(row.overall).color, background: scoreStyle(row.overall).background }}>{scoreStyle(row.overall).grade}</span></td></tr>)}</tbody></table></div><h4>مقارنة مرئية للموظفين المختارين</h4><BarChart rows={compareIds.map((id) => ranking.find((row) => row.id === id)).filter(Boolean).map((row) => ({ name: row.name, values: [row.values.digital, row.values.quality, row.values.office, row.values.discipline, row.values.initiative] }))} comparison /></div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18, marginTop: 18 }}><div style={{ ...styles.card, margin: 0 }}><h3 style={styles.cardTitle}>⭐ نقاط القوة</h3>{strengths.length ? strengths.map((item) => <div key={item.item} style={{ padding: 10, borderBottom: "1px solid #E2E8F0" }}>✅ {item.item} <strong style={{ color: "#047857" }}>{item.score}/5</strong></div>) : <div style={styles.infoBox}>لا توجد درجات تفصيلية كافية.</div>}</div><div style={{ ...styles.card, margin: 0 }}><h3 style={styles.cardTitle}>⚠️ مجالات تحتاج إلى تحسين</h3>{improvements.length ? improvements.map((item) => <div key={item.item} style={{ padding: 10, borderBottom: "1px solid #E2E8F0" }}>🔧 {item.item} <strong style={{ color: "#DC2626" }}>{item.score}/5</strong></div>) : <div style={styles.infoBox}>لا توجد عناصر منخفضة.</div>}</div></div>
      <div style={{ ...styles.card, marginTop: 18, background: selectedStyle.background, color: selectedStyle.color }}><h3 style={{ marginTop: 0 }}>📝 التوصية النهائية</h3>{selectedOverall >= 90 ? "أداء متميز ويوصى بالاستمرار على نفس المستوى." : selectedOverall >= 80 ? "أداء جيد جداً مع إمكانية تطوير بعض الجوانب." : selectedOverall >= 70 ? "أداء جيد ويحتاج إلى تحسين بعض المهارات." : "يحتاج إلى خطة تحسين ومتابعة."}</div>
    </div>
    {showForm && <div style={styles.modalOverlay} onClick={() => setShowForm(false)}><div style={{ ...styles.loginBox, maxWidth: 760, maxHeight: "90vh", overflowY: "auto" }} onClick={(event) => event.stopPropagation()}><button style={styles.closeButton} onClick={() => setShowForm(false)}>×</button><h2 style={styles.loginTitle}>إضافة تقييم تفصيلي: {selectedEmployee.name}</h2><form onSubmit={saveEvaluation}><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><input style={styles.input} type="number" min="2020" value={form.year} onChange={(event) => setForm({ ...form, year: event.target.value })} /><select style={styles.input} value={form.month} onChange={(event) => setForm({ ...form, month: Number(event.target.value) })}>{MONTHS.map((month, index) => <option key={month} value={index + 1}>{month}</option>)}</select></div>{AXES.map((axis) => <div key={axis.key} style={{ marginTop: 16 }}><strong>{axis.label} - وزن {axis.weight}%</strong>{axis.items.map((item, index) => <label key={item} style={{ display: "flex", justifyContent: "space-between", gap: 10, marginTop: 8, fontSize: 13 }}>{item}<select style={{ ...styles.input, width: 100 }} value={form.scores[axis.key][index]} onChange={(event) => { const scores = { ...form.scores, [axis.key]: [...form.scores[axis.key]] }; scores[axis.key][index] = Number(event.target.value); setForm({ ...form, scores }); }}><option value="0">لم يقيّم</option>{[1, 2, 3, 4, 5].map((score) => <option key={score} value={score}>{score} - {score === 5 ? "ممتاز" : score === 4 ? "جيد جداً" : score === 3 ? "جيد" : score === 2 ? "يحتاج تحسين" : "ضعيف"}</option>)}</select></label>)}</div>)}<textarea style={{ ...styles.input, marginTop: 14, minHeight: 70 }} placeholder="ملاحظات وتوصيات" value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /><button style={{ ...styles.primaryButton, width: "100%", marginTop: 14 }}>حفظ التقييم</button></form></div></div>}
  </div>;
}
