export const FACULTY_SALARY_CONFIG = {
  id: "faculty",
  title: "أرشيف مفردات مرتب أعضاء هيئة التدريس",
  headerEmoji: "📑",
  subtitle:
    "بحث وعرض سريع للمفردات من الأرشيف (لمسح ضوئي PDF أصلي). البحث بالاسم أو رقم الكمبيوتر مع فلاتر السنة والشهر.",
  table: "faculty_salary_archive",
  importsTable: "faculty_salary_imports",
  bucket: "faculty-salary-archive",
  storageRoot: "faculty-salaries",
  nameColumn: "faculty_name",
  memberLabel: "اسم عضو هيئة التدريس",
  memberPlaceholder: "مثال: د. أحمد محمد",
  numberLabel: "رقم الكمبيوتر",
  numberPlaceholder: "مثال: 12345",
  searchPlaceholder: "🔎 البحث بالاسم أو رقم الكمبيوتر",
  ocrNameLabel: "اسم العضو",
  ocrNumberLabel: "رقم الكمبيوتر",
  numberPattern: "(?:صرف|كمبيوتر|وظيفي|شئون|عامل|كود)",
  migrationFile: "faculty_salary_archive_section.sql",
  migrationTables: "faculty_salary_archive وfaculty_salary_imports",
  migrationBucket: "faculty-salary-archive",
  breadcrumb: "أرشيف مفردات مرتب أعضاء هيئة التدريس",
  viewTitle: "أرشيف مفردات مرتب أعضاء هيئة التدريس",
};

export const EMPLOYEE_SALARY_CONFIG = {
  id: "employee",
  title: "أرشيف مفردات مرتب الموظفين",
  headerEmoji: "👨💼",
  subtitle:
    "بحث وعرض سريع لمفردات مرتب الموظفين من الأرشيف (لمسح ضوئي PDF أصلي). البحث بالاسم أو رقم العامل مع فلاتر السنة والشهر.",
  table: "employee_salary_archive",
  importsTable: "employee_salary_imports",
  bucket: "employee-salary-archive",
  storageRoot: "employee-salaries",
  nameColumn: "employee_name",
  memberLabel: "اسم الموظف",
  memberPlaceholder: "مثال: مصطفى محمد سليمان",
  numberLabel: "رقم العامل",
  numberPlaceholder: "مثال: 035004",
  searchPlaceholder: "🔎 البحث بالاسم أو رقم العامل",
  ocrNameLabel: "اسم الموظف",
  ocrNumberLabel: "رقم العامل",
  numberPattern: "(?:عامل|صرف|كمبيوتر|وظيفي|شئون|كود)",
  migrationFile: "employee_salary_archive_section.sql",
  migrationTables: "employee_salary_archive وemployee_salary_imports",
  migrationBucket: "employee-salary-archive",
  breadcrumb: "أرشيف مفردات مرتب الموظفين",
  viewTitle: "👨💼 أرشيف مفردات مرتب الموظفين",
};